### ISSUE TITLE
How to use the dataset in the paper?

### ISSUE THREAD

**Issue by PigpigF** [yluo42/TAC#1]
Hello, I am new to speech separation by using python, can you tell me the details of using the data sets？I want to know how to input the data during training，because I have seen the code that generates the data。The data naming format is 'spk1_mic'+str(mic+1)+'.wav', so how to use multi-channel information，and how to set the batchsize ？
Thank you very much.

**Comment by yluo42** [comment]
You are asking for pretty general and basic usage of the pipeline for a machine learning project, so I'd suggest you first take a look at those tutorials about any such machine learning platforms (e.g. there are many in Pytorch's official website).

**Comment by PigpigF** [comment]
My English is not good, it may be the wrong meaning of the expression. 
我可能英语表达有错误，我想问的不是如何设置batchsize，而是具体设置为多少比较好。
