### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by KiAlexander** [yluo42/TAC#2]
your work is so awesome! I am interested in how to run this project using the model. 
would you mind update more details about running these script?

**Comment by yluo42** [comment]
You can plug the model/dataset into any of your existing training/evaluation pipelines. I intentionally only put the model implementation here as I hope that you can simply use your own pipelines without sticking to mine.

If you don't have a pipeline yet, you can also take a look at the official tutorials by Pytorch for some examples. I may also update something later.
