### ISSUE TITLE
num_mic array

### ISSUE THREAD

**Issue by shanhaidexiamo** [yluo42/TAC#6]
Hi ,I want ask you a question about the model forward func, there have two input, one is the feature called 'input', another tensor is called 'num_mic'. And I saw your example **num_mic = torch.from_numpy(np.array([3, 2])).view(-1,).type(x.type())** , is that means there have two set , one is two mics condition , another one is 3 mics condition? Suppose I use 8 channel dataset, should I set the unm_mic = np.array([8]) ? Thank you very much.

**Comment by yluo42** [comment]
Please check [this annotation](https://github.com/yluo42/TAC/blob/e1965f7d85171c4bd3cbc380cb20ddad9981343d/FaSNet.py#L169).

**Comment by shanhaidexiamo** [comment]
OK,thank you for your hint!
